# Generated by Django 4.2.7 on 2023-12-16 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='endereco',
            new_name='rua',
        ),
    ]
