# Generated by Django 5.0.1 on 2024-01-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='bairro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='complemento',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rua',
            field=models.CharField(max_length=100),
        ),
    ]
