# Generated by Django 5.0.1 on 2024-03-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_perfil_bairro_alter_perfil_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='celular',
            field=models.CharField(default=999999999, max_length=9),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ddd',
            field=models.CharField(default=31, max_length=2),
        ),
    ]
