# Generated by Django 5.0.1 on 2024-03-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_alter_perfil_cep_alter_perfil_cpf_alter_perfil_ddd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cep',
            field=models.CharField(max_length=8),
        ),
    ]
