# Generated by Django 5.0.1 on 2024-03-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_alter_perfil_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='ddd',
            field=models.CharField(default=31, max_length=2, verbose_name='Codigo de área'),
        ),
    ]
