# Generated by Django 5.0.1 on 2024-01-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossaloja', '0002_alter_loja_bairro_alter_loja_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='loja',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
