# Generated by Django 5.0.1 on 2024-03-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nossaloja', '0003_loja_latitude_loja_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='longitude',
        ),
    ]
