# Generated by Django 5.0.1 on 2024-03-11 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('data_nascimento', models.DateField(help_text='dd/mm/YYYY', verbose_name='Data de nascimento')),
                ('ddd', models.CharField(default=31, max_length=2)),
                ('celular', models.CharField(default=999999999, max_length=9)),
                ('genero', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('Estado_civil', models.CharField(choices=[('C', 'Casado(a)'), ('S', 'Solteiro(a)'), ('D', 'Divorciado(a)'), ('V', 'Viuvo(a)')], default='S', max_length=1)),
                ('nacionalidade', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='Inf_bancarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('numero_agencia', models.CharField(default=9999, max_length=4, verbose_name='Número da agência')),
                ('numero_conta', models.CharField(max_length=20, verbose_name='Número da conta')),
                ('tipo_conta', models.CharField(choices=[('1', 'Corrente'), ('2', 'Poupança'), ('3', 'Conjunta'), ('4', 'Salário'), ('5', 'Empresarial')], default='2', max_length=1, verbose_name='Tipo de conta')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaborador.perfil')),
            ],
            options={
                'verbose_name': 'Informação Bancária',
                'verbose_name_plural': 'Informações Bancárias',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=5)),
                ('complemento', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=8)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='SP', max_length=2)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaborador.perfil')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Enderoços',
            },
        ),
        migrations.CreateModel(
            name='Detalhe_cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('data_inicio', models.DateField(help_text='dd/mm/YYYY', verbose_name='Data de início do emprego')),
                ('horario_trabalho', models.CharField(choices=[('1', '7h às 17h'), ('2', '8h às 18h'), ('3', '9h às 19h'), ('4', '10h às 20h'), ('5', 'enter às 7h e 20h'), ('6', 'flexível')], default='2', max_length=1, verbose_name='Horário de trabalho')),
                ('salario', models.FloatField(verbose_name='Salário')),
                ('tipo_contrato', models.CharField(choices=[('1', 'Integral'), ('2', 'Meio Período'), ('3', 'Temporário'), ('4', 'Estagio'), ('5', 'Pessoa Jurídica')], default='2', max_length=1, verbose_name='Horário de trabalho')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaborador.perfil')),
            ],
            options={
                'verbose_name': 'Detalhe do cargo',
                'verbose_name_plural': 'Detalhes dos cargos',
            },
        ),
        migrations.CreateModel(
            name='Beneficios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficio', models.CharField(choices=[('1', 'Plano de saúde'), ('2', 'Plano Odontológico'), ('3', 'Seguro de Vida'), ('4', 'Previdência Privada'), ('5', 'Vale-Alimentação'), ('6', 'Vale-Refeição'), ('7', 'Auxílio-Educação'), ('8', 'Auxílio-Creche')], default='2', max_length=1, verbose_name='Benefício')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaborador.perfil')),
            ],
            options={
                'verbose_name': 'Benefício',
                'verbose_name_plural': 'Benefícios',
            },
        ),
    ]
