# Generated by Django 5.0.1 on 2024-03-11 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perfil',
            new_name='Perfil_colaborador',
        ),
    ]
