# Generated by Django 5.0.1 on 2024-03-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0002_rename_perfil_perfil_colaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhe_cargo',
            name='tipo_contrato',
            field=models.CharField(choices=[('1', 'Integral'), ('2', 'Meio Período'), ('3', 'Temporário'), ('4', 'Estagio'), ('5', 'Pessoa Jurídica')], default='2', max_length=1, verbose_name='Tipo de Contrato'),
        ),
    ]
