# Generated by Django 5.0.1 on 2024-03-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0003_alter_detalhe_cargo_tipo_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil_colaborador',
            name='email',
            field=models.EmailField(default='bs@email.com', max_length=254),
        ),
    ]
