# Generated by Django 5.0.1 on 2024-03-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0004_perfil_colaborador_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficios',
            name='beneficio',
            field=models.CharField(choices=[('1', 'Plano de saúde'), ('2', 'Plano Odontológico'), ('3', 'Seguro de Vida'), ('4', 'Previdência Privada'), ('5', 'Vale-Alimentação'), ('6', 'Vale-Refeição'), ('7', 'Auxílio-Educação'), ('8', 'Auxílio-Creche'), ('8', 'Vale-Transporte')], default='1', max_length=1, verbose_name='Benefício'),
        ),
    ]
