# Generated by Django 5.0.1 on 2024-03-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0005_alter_beneficios_beneficio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inf_bancarias',
            name='numero_agencia',
            field=models.CharField(help_text=9999, max_length=4, verbose_name='Número da agência'),
        ),
        migrations.AlterField(
            model_name='perfil_colaborador',
            name='celular',
            field=models.CharField(help_text=999999999, max_length=9),
        ),
        migrations.AlterField(
            model_name='perfil_colaborador',
            name='email',
            field=models.EmailField(help_text='bs@email.com', max_length=254),
        ),
    ]
