# Generated by Django 5.0.1 on 2024-03-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0006_alter_inf_bancarias_numero_agencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_colaborador',
            name='ddd',
            field=models.CharField(help_text=31, max_length=2, verbose_name='DDD'),
        ),
    ]
