# Generated by Django 5.0.1 on 2024-03-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0007_alter_perfil_colaborador_ddd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inf_bancarias',
            name='numero_agencia',
            field=models.CharField(max_length=4, verbose_name='Número da agência'),
        ),
    ]
