# Generated by Django 5.0.1 on 2024-03-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0008_alter_inf_bancarias_numero_agencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalhe_cargo',
            name='salario',
        ),
        migrations.AddField(
            model_name='perfil_colaborador',
            name='salario',
            field=models.FloatField(default=0, verbose_name='Salário'),
        ),
        migrations.AlterField(
            model_name='perfil_colaborador',
            name='Estado_civil',
            field=models.CharField(choices=[('C', 'Casado(a)'), ('S', 'Solteiro(a)'), ('D', 'Divorciado(a)'), ('V', 'Viuvo(a)')], default='S', max_length=1, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='perfil_colaborador',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
    ]
