# Generated by Django 5.0.1 on 2024-03-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0009_remove_detalhe_cargo_salario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil_colaborador',
            old_name='Estado_civil',
            new_name='estado_civil',
        ),
    ]
