# Generated by Django 3.2.25 on 2024-04-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0011_auto_20240407_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(max_length=8),
        ),
    ]
