# Generated by Django 5.0.1 on 2024-01-03 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produto_imagens')),
                ('descricao', models.TextField()),
                ('cor', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('I', 'Infantil')], default='F', max_length=1)),
                ('sub_categoria', models.CharField(choices=[('R', 'Roupa'), ('C', 'Calçados'), ('A', 'Acessórios')], default='F', max_length=1)),
                ('marca', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('preco', models.FloatField(verbose_name='Preço')),
                ('preco_minimo', models.FloatField(default=models.FloatField(verbose_name='Preço'), verbose_name='Preço Minimo.')),
            ],
        ),
        migrations.CreateModel(
            name='Variacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(max_length=3)),
                ('estoque', models.PositiveIntegerField(default=1)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
            ],
            options={
                'verbose_name': 'Variação',
                'verbose_name_plural': 'Variações',
            },
        ),
    ]
