# Generated by Django 4.2.7 on 2023-12-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('categoria', models.TextField(max_length=255)),
                ('sub_categoria', models.TextField(max_length=255)),
                ('marca', models.TextField(max_length=255)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produto_imagens')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('preco', models.FloatField(verbose_name='Preço')),
                ('preco_minimo', models.FloatField(default=models.FloatField(verbose_name='Preço'), verbose_name='Preço Promo.')),
                ('tipo', models.CharField(choices=[('V', 'Variável'), ('S', 'Simples')], default='V', max_length=1)),
            ],
        ),
    ]
