# Generated by Django 5.0.1 on 2024-01-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_rename_tamanho_variacao_nome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variacao',
        ),
    ]
