# Generated by Django 5.0.1 on 2024-01-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_produto_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco_minimo',
            new_name='preco_promocional',
        ),
    ]
