# Generated by Django 5.0.1 on 2024-01-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_rename_preco_minimo_produto_preco_promocional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_promocional',
            field=models.FloatField(default=models.FloatField(verbose_name='Preço'), verbose_name='Preço Promocional'),
        ),
    ]
