# Generated by Django 4.2.7 on 2023-12-18 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_alter_produto_categoria_alter_produto_sub_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tipo',
        ),
    ]
