# Generated by Django 4.2.7 on 2023-12-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_remove_produto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_minimo',
            field=models.FloatField(default=models.FloatField(verbose_name='Preço'), verbose_name='Preço Minimo.'),
        ),
    ]
