# Generated by Django 5.0.1 on 2024-01-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0011_alter_produto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('Outro', 'Outro'), ('Camisa', 'Camisa'), ('Cropped', 'Cropped'), ('Short', 'Short'), ('Calça', 'Calça'), ('Vestido', 'Vestido'), ('Camiseta', 'Camiseta'), ('Blazer', 'Blazer'), ('Saia', 'Saia'), ('Moletom', 'Moletom'), ('Jaqueta', 'Jaqueta'), ('Polo', 'Polo'), ('Regata', 'Regata'), ('Tênis', 'Tênis'), ('Sapato', 'Sapato'), ('Sandália', 'Sandália'), ('Rasteira', 'Rasteira'), ('Chinelo', 'Chinelo'), ('Óculo', 'Óculo'), ('Mochila', 'Mochila'), ('Bolsa', 'Bolsa'), ('Necessaire', 'Necessaire'), ('Carteira', 'Carteira'), ('Cinto', 'Cinto'), ('Boné', 'Boné')], default='Outros', max_length=30),
        ),
    ]
