# Generated by Django 5.0.1 on 2024-01-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0015_alter_produto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacao',
            name='nome',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
