# Generated by Django 5.0.1 on 2024-02-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0025_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagem',
            options={'verbose_name': 'Imagem', 'verbose_name_plural': 'Imagens'},
        ),
    ]
