# Generated by Django 5.0.1 on 2024-01-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('sobre_vaga', models.TextField()),
                ('responsabilidades', models.TextField()),
                ('requisitos', models.TextField()),
                ('beneficios', models.TextField()),
            ],
        ),
    ]
