name: Django CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test

  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 35.239.14.1 >> ~/.ssh/known_hosts

    - name: List files in the current directory
      run: ls -l

    - name: Transfer deploy.sh to server
      run: |
        scp -o StrictHostKeyChecking=no deploy.sh renorb03@35.239.14.1:/home/renorb03/deploy.sh

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no renorb03@35.239.14.1 'bash /home/renorb03/deploy.sh'
