# Generated by Django 5.0.1 on 2024-04-21 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_alter_pedido_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Pagamento Aprovado', 'Pagamento Aprovado'), ('Criado', 'Criado'), ('Pagamento Reprovado', 'Pagamento Reprovado'), ('Enviando', 'Enviando'), ('Entregue', 'Entregue'), ('Finalizado', 'Finalizado')], default='Criado', max_length=20),
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_rastreamento', models.CharField(blank=True, max_length=13, null=True)),
                ('status', models.CharField(choices=[('Processondo Entrega', 'Processondo Entrega'), ('Enviando', 'Enviando'), ('Entregue', 'Entregue')], default='Processondo Entrega', max_length=20)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
